version: 1.2
workflows:
  - name: transfer
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/TransferToGdc/TransferToGdc.wdl
  - name: delete
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/DeleteFromGdc/DeleteFromGdc.wdl
  - name: dbgapTransfer
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/TransferToDbGap/TransferFile.wdl
  - name: validateGDCStatus
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/ValidateFileStatus/ValidateFileStatus.wdl
  - name: verify
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/VerifyRegistration/VerifyRegistration.wdl
  - name: validateDbGapStatus
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/ValidateDbGapSampleStatus/ValidateDbGapSampleStatus.wdl
  
