version: 1.2
workflows:
  - name: transfer
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/TransferToGdc/TransferToGdc.wdl
  - name: delete
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/DeleteFromGdc/DeleteFromGdc.wdl
  - name: dbgapTransfer
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/TransferToDbGap/TransferFile.wdl
  - name: validateGDCStatus
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/ValidateFileStatus/ValidateFileStatus.wdl
    primaryDescriptorPath: /src/wdl/workflows/VerifyRegistration/VerifyRegistration.wdl
  - name: registerEGAExperimentAndRuns
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/RegisterEGAExperimentAndRun/RegisterEGAExperimentAndRun.wdl
  - name: registerEGADataset
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/RegisterEGADatasetFinalizeSubmission/RegisterEGADatasetFinalizeSubmission.wdl
  - name: egaFileTransfer
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/EGAFileTransfer/EGAFileTransfer.wdl
