version: 1.2
workflows:
  - name: transfer
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/TransferToGdc/TransferToGdc.wdl
  - name: delete
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/DeleteFromGdc/DeleteFromGdc.wdl
  - name: verify
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/VerifyRegistration/VerifyRegistration.wdl
  - name: register_experiment_and_runs
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/RegisterEGAExperimentAndRun/RegisterEGAExperimentAndRun.wdl
  - name: register_dataset
    subclass: WDL
    primaryDescriptorPath: src/wdl/workflows/RegisterEGADatasetFinalizeSubmission/RegisterEGADatasetFinalizeSubmission.wdl