version: 1.2
workflows:
  - name: transferToGDC
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/TransferToGdc/TransferToGdc.wdl
    readMePath: /src/wdl/workflows/TransferToGdc/README.md

  - name: deleteFromGDC
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/DeleteFromGdc/DeleteFromGdc.wdl

  - name: transferToDbgap
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/TransferToDbGap/TransferFile.wdl
    readMePath: /src/wdl/workflows/TransferToDbGap/README.md

  - name: validateGDCStatus
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/ValidateFileStatus/ValidateFileStatus.wdl
    readMePath: /src/wdl/workflows/ValidateFileStatus/README.md

  - name: validateDbGapStatus
    subclass: WDL
    primaryDescriptorPath: /src/wdl/workflows/ValidateDbGapSampleStatus/ValidateDbGapSampleStatus.wdl
    readMePath: /src/wdl/workflows/ValidateDbGapSampleStatus/README.md
  
