from enum import Enum


LIBRARY_LAYOUT = ["SINGLE", "PAIRED"]

LIBRARY_STRATEGY = [
    "WGS",
    "WGA",
    "WXS",
    "RNA-Seq",
    "ssRNA-seq",
    "miRNA-Seq",
    "ncRNA-Seq",
    "FL-cDNA",
    "EST",
    "Hi-C",
    "ATAC-seq",
    "WCS",
    "RAD-Seq",
    "CLONE",
    "POOLCLONE",
    "AMPLICON",
    "CLONEEND",
    "FINISHING",
    "ChIP-Seq",
    "MNase-Seq",
    "DNase-Hypersensitivity",
    "Bisulfite-Seq",
    "CTS",
    "MRE-Seq",
    "MeDIP-Seq",
    "MBD-Seq",
    "Tn-Seq",
    "VALIDATION",
    "FAIRE-seq",
    "SELEX",
    "RIP-Seq",
    "ChIA-PET",
    "Synthetic-Long-Read",
    "Targeted-Capture",
    "Tethered Chromatin Conformation Capture",
    "NOMe-Seq",
    "ChM-Seq",
    "GBS",
    "OTHER",
    "snRNA-seq",
    "Ribo-Seq"
]

LIBRARY_SOURCE = [
    "GENOMIC",
    "GENOMIC SINGLE CELL",
    "TRANSCRIPTOMIC",
    "TRANSCRIPTOMIC SINGLE CELL",
    "METAGENOMIC",
    "METATRANSCRIPTOMIC",
    "SYNTHETIC",
    "VIRAL RNA",
    "OTHER"
]

LIBRARY_SELECTION = [
    "RANDOM",
    "PCR",
    "RANDOM PCR",
    "RT-PCR",
    "HMPR",
    "MF",
    "repeat fractionation",
    "size fractionation",
    "MSLL",
    "cDNA",
    "cDNA_randomPriming",
    "cDNA_oligo_dT",
    "PolyA",
    "Oligo-dT",
    "Inverse rRNA",
    "Inverse rRNA selection",
    "ChIP",
    "ChIP-Seq",
    "MNase",
    "DNase",
    "Hybrid Selection",
    "Reduced Representation",
    "Restriction Digest",
    "5-methylcytidine antibody",
    "MBD2 protein methyl-CpG binding domain",
    "CAGE",
    "RACE",
    "MDA",
    "padlock probes capture method",
    "other",
    "unspecified",
]

RUN_FILE_TYPE = [
    "srf",
    "sff"
    "fastq",
    "Illumina_native",
    "Illumina_native_qseq",
    "SOLiD_native_csfasta",
    "PacBio_HDF5",
    "bam",
    "cram",
    "CompleteGenomics_native",
    "OxfordNanopore_native",
]

INSTRUMENT_MODEL = [
    "HiSeq X Five", 
    "HiSeq X Ten", 
    "Illumina Genome Analyzer",
    "Illumina Genome Analyzer II",
    "Illumina Genome Analyzer IIx",
    "Illumina HiScanSQ", 
    "Illumina HiSeq 1000",
    "Illumina HiSeq 1500",
    "Illumina HiSeq 2000",
    "Illumina HiSeq 2500",
    "Illumina HiSeq 3000",
    "Illumina HiSeq 4000",
    "Illumina HiSeq X",
    "Illumina iSeq 100",
    "Illumina MiSeq",
    "Illumina MiniSeq",
    "Illumina NovaSeq X",
    "Illumina NovaSeq 6000",
    "NextSeq 500",
    "NextSeq 550",
    "NextSeq 1000",
    "NextSeq 2000",
    "unspecified"
]
    